function displayDatasetInformation(fullpathDataDir)         

datasetID = {'obs_glob_occci_plk',...
            'obs_glob_copernicus_opt',...
            'obs_glob_copernicus_plk',...
            'obs_glob_copernicus_trns',...
            'obs_reg_opt',...
            'obs_reg_plk_olci',...
            'obs_reg_plk_multi',...
            'obs_reg_trns',...
            'mod_nws_chl',...
            'mod_nws_kd',...
            'mod_nws_diat',...
            'mod_nws_dino',...
            'mod_nws_nano',...
            'mod_nws_pico',...
            'mod_nws_phy',...
            'mod_nws_npp',...
            'mod_nws_no3',...
            'mod_nws_o2',...
            'mod_nws_po4',...
            'mod_nws_ph',...
            'mod_nws_pco2'}; 

for iDataset = 1:length(datasetID)
    filename = strcat(fullpathDataDir,datasetID{iDataset},'.nc');
    disp(filename)
    ncdisp(filename)
end

end